language: elixir
elixir:
    - 1.1.0
otp_release:
    - 18.0
addons:
  postgresql: '9.4'

before_script:
  - cp config/travis.exs config/test.exs
  - MIX_ENV=travis mix do ecto.create, ecto.migrate
script:
  - MIX_ENV=travis mix test
